# Generated by Django 3.2.8 on 2021-10-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='count_one',
            new_name='option_one_count',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='count_three',
            new_name='option_three_count',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='count_two',
            new_name='option_two_count',
        ),
    ]
